SET TERM ^ ;

CREATE OR ALTER PROCEDURE P_GET_ITEMS_BY_TAG (
    P_TAG_ID D_ID
)
RETURNS (
    ITEM_ID    D_ID,
    ITEM_NAME  D_NAME,
    ITEM_PRICE DECIMAL(15, 2)
)
AS
BEGIN
  FOR
    SELECT
        I.ITEM_ID,
        I.NAME,
        I.PRICE
    FROM ITEM I
    JOIN ITEM_TAG IT ON IT.ITEM_ID = I.ITEM_ID
    WHERE IT.TAG_ID = :P_TAG_ID
    INTO :ITEM_ID, :ITEM_NAME, :ITEM_PRICE
  DO
  BEGIN
    SUSPEND;
  END
END ^

SET TERM ; ^
