CREATE TABLE CATEGORY (
    CATEGORY_ID D_ID NOT NULL,
    NAME        D_NAME NOT NULL,
    DESCRIPTION D_DESCRIPTION,
    CREATED_AT  D_CREATED_AT,
    IS_ACTIVE   D_IS_ACTIVE,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);
