CREATE TABLE ITEM (
    ITEM_ID     D_ID NOT NULL,
    CATEGORY_ID D_ID NOT NULL,
    NAME        D_NAME NOT NULL,
    DESCRIPTION D_DESCRIPTION,
    PRICE       DECIMAL(15, 2),
    CREATED_AT  D_CREATED_AT,
    IS_ACTIVE   D_IS_ACTIVE,
    CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID)
);
